### ISSUE TITLE
toV2Operator overload missing

### ISSUE THREAD

**Issue by realdeadfish** [akarnokd/RxJava2Interop#14]
It seems to me that a `toV2Operator()` overload is missing that returns an `ObservableOperator`, not a `FlowableOperator`. Is this intended or just forgotten?

**Comment by akarnokd** [comment]
V2 `Observable`s don't support backpressure but V1 operators generally do and expect it. There is simply no good way at the `Operator` level to try and emulate backpressure if its missing on one end.

**Comment by realdeadfish** [comment]
Ok, understood - then I'll workaround it and wrap the resulting observable into a v2 observable. Thanks for clearing that up!
