### ISSUE TITLE
Not working dependencies.

### ISSUE THREAD

**Issue by m4xp1** [akarnokd/RxJava2Interop#15]
Failed to resolve.

`dependencies {
    compile "com.github.akarnokd:rxjava2-interop:0.10.0"
}`

In MavenCentral not exist, i find only 0.9.7 version.

**Comment by akarnokd** [comment]
I'm sorry, sometimes the readme is a version ahead. This time, when RxJava 1.3 is released, the interop jumps to 0.10.0. That's why there is a maven badge.
