### ISSUE TITLE
What are the impacts performance wise ?

### ISSUE THREAD

**Issue by Crystark** [akarnokd/RxJava2Interop#16]
Hi,

I'm wondering what are the performance impacts of using `RxJava2Interop`. I'm working on a project which uses RxJava 1 and I was wondering about switching to RxJava 2 for some parts. I won't be able to switch everything though so I wanted to know if there are any losses (or gains) in using both in a project through `RxJava2Interop`.

Thanks

**Comment by akarnokd** [comment]
Once connected, the interop is no more costly than a level of indirection (or an `map(v -> v)` operation would cost). v2 is much lighter than v1 with less overhead, allocation and indirection on its own. Unless you have to talk to v1-based third party libraries, I'd consider doing a full upgrade to v2.

If you are on Android, the increased method count may put you above the 64k limit. In that case, you may want to use ProGuard to trim v2.

**Comment by Crystark** [comment]
I do have connections to 3rd party libraries that haven't updated yet (and probably won't so i'll have to replace them eventually). That's why I wanted to know if i'll benefit from the partial upgrade. Am I to understand even a partial upgrade will be beneficial ?

Also FYI I'm not under Android.

**Comment by akarnokd** [comment]
Yes.

**Comment by Crystark** [comment]
Thanks!
