### ISSUE TITLE
v0.11.3 not available

### ISSUE THREAD

**Issue by Mauin** [akarnokd/RxJava2Interop#20]
Looking at jCenter and MavenCentral I cannot see version `0.11.3`. Both have `0.11.2` as their latest version.

**Comment by akarnokd** [comment]
Thanks. Looks like the release command didn't went through last time. [Now it's working](https://oss.sonatype.org/content/groups/staging/com/github/akarnokd/rxjava2-interop/0.11.3/). Should arrive on maven soon.

**Comment by Mauin** [comment]
Thanks! :)
