### ISSUE TITLE
Unsafe subscription in `ObservableV1ToObservableV2`

### ISSUE THREAD

**Issue by markotron** [akarnokd/RxJava2Interop#21]
Hi there, 

I'm trying to wrap the RxBleAndroid library (which uses RxJava1) so I can use it in my RxJava2 application. A simple wrapper function looks like this: 
```
fun establishConnection(): Observable<BleConnection> =
    RxJavaInterop.toV2Observable(rxBleDevice.establishConnection(false))
```
 - The `rxBleDevice.establishConnection(false)` returns an observable that clears its resources on unsubscribe (`doOnUnsubscribe`).
 - If you try to subscribe twice on this observable, without clearing the resources, you'll get `BleAlreadyConnectedException`.  
 - When the BLE device is two far (or it's not advertising) this observable errors out with `BleDisconectedException`

Now, if you subscribe safely to this observable, everything works as expected. When the observable errors with `BleDisconectedException`, it unsubscribes and cleans all the resources, now you can easily subscribe again without getting `BleAlreadyConnectedException`. 

On the other hand, if you use `unsafeSubscribe` the resources are not released when the error happens which means that I can't subscribe again (I get the `BleAlreadyConnectedException`).

Is there a reason why `ObservableV1ToObservableV2` unsafely subscribes in its `subscribeActual` function?

Thanks.

**Comment by akarnokd** [comment]
A simple oversight. I'll post a fix shortly.

**Comment by markotron** [comment]
Ok cool! I wanted to submit a PR but I had some problems including this library into my app to test it. Sorry about that :/

**Comment by akarnokd** [comment]
Closing via [0.11.4](https://github.com/akarnokd/RxJava2Interop/releases/tag/v0.11.4). The library should arrive in maven within a few hours.
