### ISSUE TITLE
[Question] Using schedulers interop to share Rx 1 and Rx 2 schedulers.

### ISSUE THREAD

**Issue by tonycosentini** [akarnokd/RxJava2Interop#24]
(This isn't really an issue, just a question - apologies if this is not the best forum for this.)

We have a relatively large Android codebase with mostly Rx 2 code, but also a decent chunk of Rx 1 code hanging around.

I recently noticed the new schedulers interop API, and I was curious if there would be any downside to simply setting our default Rx 2 I/O and computation schedulers to simply point to interop'd Rx 1 schedulers.

For us, this would be beneficial since everything would share one thread pool. However, I was curious if there might be any subtle gotchas for using this interop API for nearly everything (particularly since it seems like some of the scheduler contracts are bit different in Rx 1 vs Rx 2).

Thanks!

**Comment by artem-zinnatullin** [comment]
You probably want to point to RxJava 2 schedulers tho, RxJava 1 is reaching [end-of-life](https://github.com/ReactiveX/RxJava/issues/5854) so why point to RxJava 1 schedulers :)

**Comment by akarnokd** [comment]
If you don't have customized v1 Schedulers then it is fine to hook up v2 Schedulers. If you or @artem-zinnatullin  wants to, a method could be added on the interop class that does this for you.

**Comment by tonycosentini** [comment]
In our case, they are mostly stock-ish. Should be easy to port over to Rx 2. I'll take a look at how the Rx 2 -> 1 scheduler API works and see if I can do the reverse.

**Comment by tonycosentini** [comment]
Going to close this since the question is answered - feel free to reopen if there's any reason to keep this around.

**Comment by tonycosentini** [comment]
> If you don't have customized v1 Schedulers then it is fine to hook up v2 Schedulers. If you or @artem-zinnatullin wants to, a method could be added on the interop class that does this for you.

Actually looks like this already exists - https://github.com/akarnokd/RxJava2Interop/blob/master/src/main/java/hu/akarnokd/rxjava/interop/RxJavaInterop.java#L664
