### ISSUE TITLE
RxJava 2.2.4 breaks FlowableV2ToObservableV1

### ISSUE THREAD

**Issue by AndrewWestberg** [akarnokd/RxJava2Interop#26]
Cannot resolve method: io.reactivex.internal.subscriptions.SubscriptionHelper.isCancelled()

**Comment by akarnokd** [comment]
Thanks for reporting. I'll post a new version shortly.

**Comment by akarnokd** [comment]
Closing via https://github.com/akarnokd/RxJava2Interop/releases/tag/v0.13.4
