### ISSUE TITLE
Rx1 observable is subscribed to even if downstream operator cancels the subscription

### ISSUE THREAD

**Issue by kennymacleod** [akarnokd/RxJava2Interop#27]
It appears that `ObservableV1ToObservableV2` is not taking into account the situation where a downstream operator cancels the subscription.

I've written a test case (below) which tests 2 setups:

* Create an Rxjava2 Observable using `fromCallable`, and apply an operator to it that disposes of the subscription during `onSubscribe`
* Create an Rxjava1 Observable using `fromCallable`, convert it to Rx2 via `RxJavaInterop`, then apply the same operator 

In both cases, I'd expect the `Callable` to never be invoked, and this is indeed what happens in the pure rx2 case. In the interop case, however, the `Callable` is invoked.

I think the problem lies in `ObservableV1ToObservableV2#subscribeActual`:

```
    protected void subscribeActual(io.reactivex.Observer<? super T> s) {
        ObservableSubscriber<T> parent = new ObservableSubscriber<T>(s);
        s.onSubscribe(parent);

        source.unsafeSubscribe(parent);
    }
```

I'm thinking that following the `s.onSubscribe(parent)`, it should check the status of the subscription before calling `source.unsafeSubscribe(parent)`, only doing so if the subscription is still active.

Here's my test case:

```
import hu.akarnokd.rxjava.interop.RxJavaInterop;
import io.reactivex.Observable;
import io.reactivex.ObservableOperator;
import io.reactivex.Observer;
import io.reactivex.disposables.Disposable;
import org.junit.jupiter.api.Test;

import java.util.concurrent.Callable;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

class InteropBugTest {

    @Test
    public void testRx2() throws Exception {
        final Callable<String> action = mock(Callable.class);
        final Observable<String> observable = Observable.fromCallable(action);

        observable.lift(operatorThatDisposes())
                  .test()
                  .assertComplete();

        verify(action, never()).call();
    }

    @Test
    public void testRx1Interop() throws Exception {
        final Callable<String> action = mock(Callable.class);
        final rx.Observable<String> observable = rx.Observable.fromCallable(action);

        observable.to(RxJavaInterop::toV2Observable)
                  .lift(operatorThatDisposes())
                  .test()
                  .assertComplete();

        verify(action, never()).call();
    }

    private static <T> ObservableOperator<T, T> operatorThatDisposes() {
        return observer -> new Observer<T>() {
            @Override
            public void onSubscribe(final Disposable d) {
                d.dispose();
                observer.onComplete();
            }

            @Override
            public void onNext(final T s) {
                observer.onNext(s);
            }

            @Override
            public void onError(final Throwable e) {
                observer.onError(e);
            }

            @Override
            public void onComplete() {
                observer.onComplete();
            }
        };
    }
}
```

**Comment by akarnokd** [comment]
> I'm thinking that following the s.onSubscribe(parent), it should check the status of the subscription before calling source.unsafeSubscribe(parent)

We almost never do this in any RxJava version. Use `onTerminateDetach` on either side to make cancellation more eager.

**Comment by kennymacleod** [comment]
Thanks for the quick feedback, although I'm struggling to see how `onTerminateDetach` relates this. Could you point where in the test case this would be done?

**Comment by akarnokd** [comment]
If you want cancellation to stop signals more eagerly, use `onTerminateDetach`. If you want to prevent subscription from propagating due to an eager cancel from `onSubscribe`, you'd have to write an operator or use composition, such as

```java
        AtomicInteger cnt = new AtomicInteger();
        
        Callable<Integer> a = () -> cnt.incrementAndGet(); 
        Observable.fromCallable(() -> a)
        .map(v -> v.call())
        .test(true)
        .assertEmpty();
        
        Assert.assertEquals(0, cnt.get());
```
