### ISSUE TITLE
Add Maybe support?

### ISSUE THREAD

**Issue by JakeWharton** [akarnokd/RxJava2Interop#3]
There's no direct analogous, but I'd be curious if you think there's value in providing a method to directly map it to a V1 `Observable`. The alternative is to force users to widen the type to V2's `Observable` or `Flowable` before calling into this library for conversion.

**Comment by akarnokd** [comment]
I can imagine v1 Single to v2 Maybe and v1 Completable to v2 Maybe and vice versa (where Maybe -> v1 Single may yield NoSuchElementException).

**Comment by JakeWharton** [comment]
I can PR that if you'd like.

**Comment by akarnokd** [comment]
Sure, go ahead.

**Comment by akarnokd** [comment]
Closing via #4 and https://github.com/akarnokd/RxJava2Interop/commit/ae8242479631655d095cdf7e77def54d5781c042 .
