### ISSUE TITLE
Is RxJava2 still supported?

### ISSUE THREAD

**Issue by voddan** [akarnokd/RxJava2Interop#36]
It seems that there are 2 public artifacts `com.github.akarnokd:rxjava2-interop` and `com.github.akarnokd:rxjava3-interop`, both of which work.

The Readme seems to only mention RxJava3. Has RxJava2 adapter been dropped, or is it still supported alongside RxJava3?

**Comment by akarnokd** [comment]
The library is pretty much feature complete so I no longer update the dependencies on `rxjava2-interop`. You may have to import the most recent RxJava 2 version and not rely on the transient dependency of this library.

RxJava 3 is changing significantly enough so I have to release a fresh `rxjava3-interop` whenever RxJava gets a new release.

**Comment by voddan** [comment]
I see, thank you!

It was a bit less straightforward to discover the `rxjava2-interop` than the rx3 version. IMHO mentioning it the Readme would greatly help.
