### ISSUE TITLE
Adapt functional interfaces

### ISSUE THREAD

**Issue by f2prateek** [akarnokd/RxJava2Interop#5]
There are some changes in v1's functional interfaces. For instance,`rx.functions.Action0` is now `io.reactivex.functions.Action`.

Is in the scope of this library to be able to adapt between the two versions?

Here's what a `rx.functions.Action0` to `io.reactivex.functions.Action` adapter would look like:

```java
public static io.reactivex.functions.Action toV2Action(final rx.functions.Action0 action) {
        io.reactivex.internal.functions.ObjectHelper.requireNonNull(action, "action is null");
        return new Action0V1ToActionV2(action);
}

... 

final class Action0V1ToActionV2 implements io.reactivex.functions.Action {
  final rx.functions.Action0 action;

  Action0V1ToActionV2(Action0 action) {
    this.action = action;
  }

  @Override public void run() throws Exception {
    action.call();
  }
}
```

**Comment by akarnokd** [comment]
This library adapts between the reactive base types only. Everything else is out of scope.

**Comment by f2prateek** [comment]
Cool, is there any value in providing adapters for the functional interfaces as a seperate library? Or am I missing something and this isn't really needed?

**Comment by akarnokd** [comment]
With Java 8 or Retrolambda, you can simply convert between the two with the `::` operator:

```java
Func1<Integer, Integer> f1 = v -> v + 1;

Function<Integer, Integer> f2 = f1::call;
```

**Comment by f2prateek** [comment]
Ah that's easy enough to do without needing custom adapters.
