### ISSUE TITLE
rxjava3-interop OSGI bundle doesn't start due to imports of internal packages

### ISSUE THREAD

**Issue by feffef** [akarnokd/RxJava2Interop#55]
I tried using the rxjava3-interop library (version 3.0.0) in a project that runs in an OSGi container (Apache Felix)

The problem I ran into is that the rxjava3-interop bundle won't start due to the imports of the following packages 

    io.reactivex.rxjava3.internal.disposables -- Cannot be resolved
    io.reactivex.rxjava3.internal.subscriptions -- Cannot be resolved
    io.reactivex.rxjava3.internal.util -- Cannot be resolved

This happens because those packages aren't exported by the rxjava bundle (io.reactivex.rxjava3/rxjava/3.0.3).

Since I think that these packages are intentionally not exported, would it be possible to get rid of these imports in the rxjava3-interop bundle (without adding/duplicating too much code)?

**Comment by akarnokd** [comment]
Sure.

**Comment by akarnokd** [comment]
Fixed via [3.0.1](https://github.com/akarnokd/RxJavaInterop/releases/tag/v3.0.1). Should be available from maven in an hour.

**Comment by feffef** [comment]
Thank you so much! I tried the 3.0.1 release, and the original issue is indeed fixed. 

However I did miss one other thing that prevents me from using the rxjava3-interop library as an OSGI bundle. The bundle does not export any package at all:

The META-INF/MANIFEST.MF in the jar does not contain an "Export-Package" entry, instead it just contains this
    Private-Package: hu.akarnokd.rxjava3.interop

I'm sorry that I missed this earlier - could you extend the bnd configuration so that the hu.akarnokd.rxjava3.interop package is exported?

**Comment by akarnokd** [comment]
Will this work for you?

```
Export-Package: hu.akarnokd.rxjava3.interop;uses:="io.reactivex.rxjava
 3.annotations,io.reactivex.rxjava3.core,io.reactivex.rxjava3.disposab
 les,io.reactivex.rxjava3.processors,io.reactivex.rxjava3.subjects,org
 .reactivestreams,rx,rx.subjects";version="3.0.2"
```

**Comment by feffef** [comment]
Yes, that looks good to me. I also confirmed that the exports/imports work as expected in Apache Felix when I add that line to the  MANIFEST.MF of the 3.0.1 release jar.

**Comment by akarnokd** [comment]
Done.

**Comment by feffef** [comment]
Awesome! With release 3.0.2 everything works as expected - thanks a lot for your quick support.
