### ISSUE TITLE
How does the conversion work regarding Nulls values handling?

### ISSUE THREAD

**Issue by danielesegato** [akarnokd/RxJava2Interop#7]
In issue https://github.com/ReactiveX/RxJava/issues/4644 has been discussed about one of the biggest feature change in RxJava 2.0: removal support for Nulls value. `onNext(null)` is supposed to throw a `NullPointerException`.

How is this handled when converting an RxJava 1.0 Observable to an RxJava 2.0 Observable?

Thanks

**Comment by danielesegato** [comment]
Sorry I went into looking the code:

https://github.com/akarnokd/RxJava2Interop/blob/master/src/main/java/hu/akarnokd/rxjava/interop/ObservableV1ToObservableV2.java#L58

```
            if (t == null) {
                unsubscribe();
                onError(new NullPointerException(
                    "The upstream 1.x Observable signalled a null value which is not supported in 2.x"));
            } else {
                actual.onNext(t);
            }
```

Does this mean there's no way to use RxJava 2.0 on 1.0 libraries that DO return nulls in their values?

Will mapping the 1.x Observable to an `Optionable<>` before converting work?

**Comment by akarnokd** [comment]
You need an additional step to hide a null, for example 

  - wrapping the 1.x value into an 1.x `Notification` object
  - wrapping via `java.util.Optional` on Java 8+
  - using a sentinel value, changing the flow type to `Object` and then casting back to your type on the 2.x side.
